<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog - Abhiraj Shrotriya</title>

    <link rel="stylesheet" href="./css/blog.css">
    <link rel="stylesheet" href="./css/blogMobile.css" media="screen and (max-width: 768px)">
</head>
<body>
    <header>
        <h1><a href="./index.php">ABHIRAJ SHROTRIYA</a></h1>

        <nav role="navigation">
            <ul>
                <li><a href="./about_me.html">ABOUT</a></li>
                <li><a href="./education.html">EDUCATION</a></li>
                <li><a href="./experience.html">EXPERIENCE</a></li>
                <li><a href="./projects.html">PROJECTS</a></li>
                <li><a href="./skills.html">SKILLS</a></li>
                <li><a href="./contact.html">CONTACT</a></li>
                <li><a href="./blog.php" id="current">BLOG</a></li>
            </ul>
        </nav>
        
        <aside id="logged_out_side">
            <br>
            <a href="./addEntry.php">Add Blog Entry</a>
            <br>
            <br>
            <form action='blog.php' method='get'>
                <fieldset>
                    <label for='month'>Month</label>
                    <select name='month' id='month'>
                        <?php 
                            
                            session_start();
                            $selectedMonth = $_GET['month'];

                            $months = array("All", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");

                            for($i=0; $i<=12; $i++){
                                if($selectedMonth == $i){
                                    echo "<option value='".$i."' selected>".$months[$i]."</option>";
                                }
                                else{
                                    echo "<option value='".$i."'>".$months[$i]."</option>";
                                }
                            }
                        ?>
                    </select>

                    <input type='submit' id='monthSubmit' name='monthSubmit' value='Filter By Month'>
                </fieldset>
            </form>
        </aside>

        <?php 
            session_start();
            if(isset($_SESSION['firstName'])){
                echo "<aside id='logged_in_side'>";
                echo "Welcome <br> <p>".$_SESSION['firstName']." ".$_SESSION['lastName']."</p>";
                echo "<br>";
                echo "<a href='./logout.php'>LOGOUT</a>";
                echo "<br>";
                echo "<br>";
                echo "<a href='./addEntry.php'>Add Blog Entry</a>";
                echo "<br>";
                echo "<br>";
                echo "<form action='blog.php' method='get'> <fieldset> <label for='month'>Month</label>";
                echo "<select name='month' id='month'>";

                session_start();
                $selectedMonth = $_GET['month'];

                $months = array("All", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");

                for($i=0; $i<=12; $i++){
                    if($selectedMonth == $i){
                        echo "<option value='".$i."' selected>".$months[$i]."</option>";
                    }
                    else{
                        echo "<option value='".$i."'>".$months[$i]."</option>";
                    }
                }

                echo " </select>";
                echo " <input type='submit' id='monthSubmit' name='monthSubmit' value='Filter By Month'> </fieldset> </form>";

                echo '</aside>';
            }
        ?>
        
    </header>

    <article>
        <?php
            $servername = "127.0.0.1";
            $username = "root";
            $password = "root";
            $dbname = "myWebsite";
        
            $conn = new mysqli($servername, $username, $password, $dbname);
        
            if ($conn->connect_error) {
                die("Connection failed: " . $conn->connect_error);
            }

            $sql = "SELECT * FROM POSTS";
        
            $ret = $conn->query($sql);

            if($ret->num_rows == 0){
                header("Location: addEntry.php");
            }

            $blogs_raw = array();
            $blogs_sorted = array();

            $row = $ret->fetch_assoc();
            while($row != null){

                $title = $row['title'];
                $content = $row['content'];
                $datetime = $row['datetime'];

                $blogs_raw[] = array($title, $datetime, $content);
                $row = $ret->fetch_assoc();
            }
            
            // Generated by Co-pilot -- START
            // Filter by month algorithm
            $monthNum = $_GET['month'];

            for ($i = 0; $i < count($blogs_raw); $i++) {
                if ($monthNum === null) {
                    $blogs_sorted[] = $blogs_raw[$i];
                }
                elseif ($monthNum == 0) {
                    $blogs_sorted[] = $blogs_raw[$i];
                }
                else {
                    $formattedMonthNum = sprintf("%02d", $monthNum);
                    if (substr($blogs_raw[$i][1], 5, 2) === $formattedMonthNum) {
                        $blogs_sorted[] = $blogs_raw[$i];
                    }
                }
            }
            
            // Generated by Co-pilot -- END

            

            // Generated by Co-pilot -- START

            // Bubble sort
            for ($i = 0; $i < count($blogs_sorted) - 1; $i++) {
                for ($j = 0; $j < count($blogs_sorted) - $i - 1; $j++) {
                    if ($blogs_sorted[$j][1] < $blogs_sorted[$j + 1][1]) {
                        // Swap the elements
                        $temp = $blogs_sorted[$j];
                        $blogs_sorted[$j] = $blogs_sorted[$j + 1];
                        $blogs_sorted[$j + 1] = $temp;
                    }
                }
            } 
            
            // Generated by Co-pilot -- END

            
            for($i = 0; $i < count($blogs_sorted); $i++){

                if(substr($blogs_sorted[$i][1], 5, 2) == '01'){
                    $monthFormat = "January";
                }
                if(substr($blogs_sorted[$i][1], 5, 2) == '02'){
                    $monthFormat = "February";
                }
                if(substr($blogs_sorted[$i][1], 5, 2) == '03'){
                    $monthFormat = "March";
                }
                if(substr($blogs_sorted[$i][1], 5, 2) == '04'){
                    $monthFormat = "April";
                }
                if(substr($blogs_sorted[$i][1], 5, 2) == '05'){
                    $monthFormat = "May";
                }
                if(substr($blogs_sorted[$i][1], 5, 2) == '06'){
                    $monthFormat = "June";
                }
                if(substr($blogs_sorted[$i][1], 5, 2) == '07'){
                    $monthFormat = "July";
                }
                if(substr($blogs_sorted[$i][1], 5, 2) == '08'){
                    $monthFormat = "August";
                }
                if(substr($blogs_sorted[$i][1], 5, 2) == '09'){
                    $monthFormat = "September";
                }
                if(substr($blogs_sorted[$i][1], 5, 2) == '10'){
                    $monthFormat = "October";
                }
                if(substr($blogs_sorted[$i][1], 5, 2) == '11'){
                    $monthFormat = "November";
                }
                if(substr($blogs_sorted[$i][1], 5, 2) == '12'){
                    $monthFormat = "December";
                }

                if(substr($blogs_sorted[$i][1], 8, 2) == '01'){
                    $dateFormat = "1st";
                }
                if(substr($blogs_sorted[$i][1], 8, 2) == '02'){
                    $dateFormat = "2nd";
                }
                if(substr($blogs_sorted[$i][1], 8, 2) == '03'){
                    $dateFormat = "3rd";
                }
                if(substr($blogs_sorted[$i][1], 8, 2) >= '04'){
                    if(substr($blogs_sorted[$i][1], 8, 2) <= '20'){
                        $dateFormat = substr($blogs_sorted[$i][1], 8, 2) . "th";
                    }
                }
                if(substr($blogs_sorted[$i][1], 8, 2) == '21'){
                    $dateFormat = "21st";
                }
                if(substr($blogs_sorted[$i][1], 8, 2) == '22'){
                    $dateFormat = "22nd";
                }
                if(substr($blogs_sorted[$i][1], 8, 2) == '23'){
                    $dateFormat = "23rd";
                }
                if(substr($blogs_sorted[$i][1], 8, 2) >= '24'){
                    $dateFormat = substr($blogs_sorted[$i][1], 8, 2) . "th";
                }

                $datetimeFormat = "🕑" . $dateFormat . " " . $monthFormat . " " . substr($blogs_sorted[$i][1], 0, 4) . ", " . substr($blogs_sorted[$i][1], 11, 5) . " BST";
                echo "<section> <div> <h2>". $blogs_sorted[$i][0] . "</h2> <p>". $datetimeFormat . "</p> </div> <p>". $blogs_sorted[$i][2] . "</p> </section>";
            }

            $conn->close();
        ?>
    </article>

    <footer>

        <div>
            <div>
                <ul>
                    <li><a href="./about_me.html">About</a></li>
                    <li><a href="./loginForm.php">Login/Sign up</a></li>
                    <li><a href="./contact.html">Contact</a></li>
                </ul>

                <div>
                    <a href=""><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/480px-LinkedIn_logo_initials.png" alt="Linkedin"></a>
                    <a href=""><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/1200px-Instagram_icon.png" alt="Instagram"></a>
                </div>
            </div>
            <address>
                <a href="mailto: sidedphoneofgriff@gmail.com">sidedphoneofgriff@gmail.com</a>
                <a href="tel: +44 79xxxxxxxx">+44 79XX50XX95</a>
                1XX GAR LAN WNDSWRT LONDON UK
            </address>
            <p>Abhiraj Shrotriya © 2024</p>
        </div>
    </footer>
</body>
</html>